### ISSUE TITLE
增加backgroundimage什么时候可以使用啊

### ISSUE THREAD

**Issue by yanbin218** [ChrisChan13/wxml2canvas-2d#1]

**Comment by ChrisChan13** [comment]
正在逐步支持哦~ 可以考虑先使用普通的 image 标签实现具体需求~

**Comment by ChrisChan13** [comment]
久等啦~ `background-image` 等相关样式在新版本 `v1.0.2` 中已经支持使用啦~

<table>
  <tr>
    <td colspan="2">background-image</td>
    <td>背景图像，支持</td>
  </tr>
  <tr>
    <td rowspan="2">background-position</td>
    <td>background-position-x</td>
    <td>背景图像水平方向的位置，支持</td>
  </tr>
  <tr>
    <td>background-position-y</td>
    <td>背景图像垂直方向的位置，支持</td>
  </tr>
  <tr>
    <td colspan="2">background-size</td>
    <td>背景图像的大小，支持</td>
  </tr>
  <tr>
    <td colspan="2">background-repeat</td>
    <td>背景图像的重复方式，暂不支持 space 和 round</td>
  </tr>
</table>
