### ISSUE TITLE
求支持text-shadow

### ISSUE THREAD

**Issue by vaint** [ChrisChan13/wxml2canvas-2d#10]
如题，跪谢。
另外请问博主有技术文章的小红书或公众号吗？我可以关注一波

**Comment by ChrisChan13** [comment]
感谢您的使用与提出的建议！对于 text-shadow 的支持，我马上着手开发！

**Comment by ChrisChan13** [comment]
@vaint 哈喽~ 关于 text-shadow 的建议，已在 `^1.0.10` 版本中实现哦，请更新版本后查看！
