### ISSUE TITLE
border-radius 形变。

### ISSUE THREAD

**Issue by XingFan0** [ChrisChan13/wxml2canvas-2d#11]
设置border-radius 时，使用真机调试，会发生形变，有没有什么解决方法嘛？
![Uploading 1.png…]()

**Comment by ChrisChan13** [comment]
你好，方便的话可以提供一下代码片段吗？另外附带的图片链接是失效的

**Comment by ChrisChan13** [comment]
你好，方便的话可以提供一下代码片段吗？另外附带的图片链接是失效的 @XingFan0

**Comment by XingFan0** [comment]
@ChrisChan13 我下载库之后，把demo copy下来运行，然后运行到真机。

**Comment by XingFan0** [comment]
https://www.gdgold.net.cn/mall-wx/wx/storage/fetch/9cgz52t2yj0hrbhjb7iy.png

**Comment by ChrisChan13** [comment]
请问你的真机设备的系统、微信版本、微信版本库是多少呢？初步认为有可能是版本兼容的问题

**Comment by XingFan0** [comment]
iPhone13pro  iOS17.0.1  微信版本：8.0.54  基础库：3.6.6

**Comment by ChrisChan13** [comment]
你可以试一下，删除组件代码 canvas.js，clipElementPath 方法中，如下图红框内的关于 iOS 的判断代码，然后再在你的设备上运行看一看

![image](https://github.com/user-attachments/assets/347796d1-791d-4d09-a8b3-6c143c9c05c4)

**Comment by XingFan0** [comment]
非常感谢，这种方式可以了。 @ChrisChan13

**Comment by ChrisChan13** [comment]
不客气！不过这段代码也不能简单的删除，而是需要加上判断版本库。因为旧的 iOS 设备或版本，还需要依赖这个判断，才能正确绘制 border-radius。应该是微信近期的更新，修复了这个 iOS 与 Android 参数不一致的 BUG。 @XingFan0

**Comment by XingFan0** [comment]
好的，谢谢大佬，后续会更新版本嘛？ @ChrisChan13

**Comment by ChrisChan13** [comment]
当然会的！不过还需要测试一下，微信到底是在哪个版本、哪个基础库修复了这个 BUG，真是头大~

**Comment by XingFan0** [comment]
感谢大佬。

**Comment by ChrisChan13** [comment]
@XingFan0  哈喽，已在 `v1.1.5` 中修复此问题！测试了几个不同的 iOS 版本、微信版本以及基础库版本，均发现有相同的问题。可能微信已经全面修复前面提到的 BUG，所以此次更新仅删除了相关的 iOS 设备判断

**Comment by XingFan0** [comment]
@ChrisChan13 非常感谢，膜拜大佬。
