### ISSUE TITLE
ios 生成空白

### ISSUE THREAD

**Issue by Lick-liu** [ChrisChan13/wxml2canvas-2d#3]

**Comment by ChrisChan13** [comment]
你好，方便的话可以提供一下代码片段吗？

**Comment by Lick-liu** [comment]
就你的示例在ios上都会生成失败

**Comment by ChrisChan13** [comment]
你好，经测试发现：小程序中部分 iOS 系统对于 `Path2D` 的支持度不足，并且 `Path2D.ellipse` 的参数 `rotation`（旋转角度）的取值类型与 Android 不同（前者支持传入角度值，后者支持传入弧度值）。`Path2D` 用于 `CanvasContext.clip` 设定各 Canvas 元素的边界范围，由于上述 BUG 导致边界绘制错误，从而内容被剪切，目前我已在最新版本中修复。

**Comment by Lick-liu** [comment]
好的，谢谢大佬
