### ISSUE TITLE
scale缩放bug

### ISSUE THREAD

**Issue by littlebearGreat** [ChrisChan13/wxml2canvas-2d#5]
你好，scale的默认值是1，我配置为其它参数时，绘制时缩放了，但是画布大小没有缩放，会导致绘制内容与画布大小不匹配

**Comment by ChrisChan13** [comment]
您好，不是很明确你所描述的大小不匹配问题。以下是我在**未合并**你提交的 PR #6 的情况下，调整 `scale` 倍数所生成的预览图，表现正常：

![image](https://github.com/ChrisChan13/wxml2canvas-2d/assets/27924290/76ddc153-9097-4b0b-aae8-bba931883325)

另外在你提交的 PR #6 中，对于组件 data 中的 `canvasWidth` 和 `canvasHeight` 根据 `scale` 倍数缩放的修改，其实是修改了 Canvas 在 **DOM 结构中**样式的宽高大小：
```html
<canvas
  type="2d"
  id="wxml2canvas"
  class="wxml2canvas box-class"
  style="width: {{canvasWidth}}px; height: {{canvasHeight}}px;"
/>
```

而绘制时的 Canvas 大小已在 `Canvas` 类中的 `init` 方法内根据 `scale` 倍数进行缩放，此处的 `width` 和 `height` 设置才是对 Canvas **最终大小**的设置（此处宽高与 CSS 样式中的宽高各自生效）：
```javascript
/**
 * 初始化
 * @param {NodesRef} container 容器元素节点信息
 * @param {Number} scale 画布缩放倍数
 */
async init(container, scale = 1) {
  const canvas = this.canvas = await getCanvas(this.component, this.selector);
  scale *= SYS_DPR;
  canvas.width = container.width * scale;
  canvas.height = container.height * scale;
  const ctx = this.context = canvas.getContext('2d');
  ctx.scale(scale, scale);
  ctx.translate(-container.left, -container.top);
  ctx.save();
}
```

关于需不需要对该 Canvas 在 DOM 结构中样式的宽高大小进行缩放：
1. 首先该 Canvas 默认**在视窗内不可见**，此项目是*基于界面中已有的 DOM 结构和 CSS 样式*，转换生成 Canvas 并导出图片。若将该 Canvas 展示于视窗内，就与界面上已有的内容重复；
2. 如果非要将该 Canvas 展示于视窗内，保持原有比例大小即可。即使对该 Canvas 的宽高样式进行缩放，也会造成视窗内的内容排版或布局变化，甚至放大导致视窗内无法完整显示整个 Canvas；
3. 最后其实如果没有于视窗内展示该 Canvas 的需求，对于 Canvas 的宽高样式进行设置，本来就是非必要的操作，绘制前已于 `Canvas` 类中的 `init` 方法设置其宽高。

**Comment by littlebearGreat** [comment]
不好意思，我忘了描述前提了。我测试在微信开发者工具、安卓设备下的微信小程序都没有问题，但是在PC版微信小程序下会出现这样的问题。具体复现方法：微信开发者工具-预览-复制预览二维码发送到微信文件传输助手-在电脑微信上打开二维码右键识别二维码-打开小程序。这个可能是微信电脑版的一个bug，具体问题我没有定位，只是简单的根据scale倍数改了一下canvas dom的尺寸就发现可以解决这个问题。另外我也看了Canvas类中的init方法，有设置其宽高。

**Comment by ChrisChan13** [comment]
您好，经过测试发现确实在 Windows 平台小程序中存在该问题，目前定位为 `wx.canvasToTempFilePath` 的 **BUG**。Windows 平台小程序的 Canvas 在使用该 API 导出临时路径时，未正确处理（同步）位于 `Canvas` 类中 `init` 方法对于 Canvas 的 width 和 height 的修改，导致所导出图片的尺寸不对，具体表现为：
- 设置 `scale` 小于 1 时，导出图片有留白；
- 设置 `scale` 大于 1 时，导出图片发生截取。

<img src="https://github.com/ChrisChan13/wxml2canvas-2d/assets/27924290/3a5f4356-1dff-4c56-a842-24f782a88102" width=200>
<img src="https://github.com/ChrisChan13/wxml2canvas-2d/assets/27924290/4d1981a0-7eaa-4ce9-887c-e0fe9875ec42" width=200>

图一为设置了 `scale` 为 2 的原 DOM 结构与样式；
图二通过修改样式将组件中的画布显示在视窗内，并执行绘制的操作；
由此可见，缩放后 Canvas 的绘制的确没有问题，问题出在 `wx.canvasToTempFilePath`。

若在 `Canvas` 类中的 `toTempFilePath` 方法修改 `wx.canvasToTempFilePath` 的参数，传入实际绘制时的宽高：
```javascript
/** 导出画布至临时图片 */
async toTempFilePath() {
  const { tempFilePath } = await wx.canvasToTempFilePath({
    canvas: this.canvas,
    width: this.canvas.width, // 传入实际绘制时的宽度
    height: this.canvas.height, // 传入实际绘制时的高度
    fileType: 'png',
  }, this.component);
  return tempFilePath;
}
```
此方法虽然可以解决设置 `scale` 小于 1 时缩小画布的情况，但在设置 `scale` 大于 1 时，却无法生效。由于 Windows 平台小程序在导出图片时未同步 width 和 height 的设置，此时绘制的 Canvas 宽高已经突破该 Canvas 原本的宽高，所以导出总是发生截取。

估计 `wx.canvasToTempFilePath` 采用的还是旧版微信 Canvas 画布的逻辑，没有适配好新的 Canvas 2D 类型，这个问题得等微信修复。同时我会尝试其他解决方案，若无法修复这个问题，将采用你提交的 PR #6 。因为组件中的画布仅是通过定位隐藏于视窗之外，而动态根据缩放倍数改变 DOM 结构中 Canvas 的宽高样式，容易因为放大意外出现、影响视窗内的原有界面。

感谢你指出的问题，有更多想法欢迎再次提交 PR~
