### ISSUE TITLE
display: flex;，在真机中，数字会被遮挡

### ISSUE THREAD

**Issue by wangsongjie** [ChrisChan13/wxml2canvas-2d#7]
如下代码，1不显示。

**Comment by wangsongjie** [comment]
`<view class="content wxml2canvas-container">
  <view class="wxml2canvas-item" style="display: flex;justify-content: center;">
      <view class="wxml2canvas-item" data-text="1">
        1
      </view>
      <view class="wxml2canvas-item" data-text="测试">测试</view>
    </view>
</view>`

**Comment by wangsongjie** [comment]
![Uploading 微信图片_20240511165502.jpg…]()

**Comment by wangsongjie** [comment]
![微信截图_20240511165404](https://github.com/ChrisChan13/wxml2canvas-2d/assets/9547222/beffa32c-2f71-45e6-abf6-59a7697a09a9)

**Comment by wangsongjie** [comment]
![Uploading 微信图片_20240511165502.jpg…]()

**Comment by ChrisChan13** [comment]
你好，经测试并非 `display: flex` 的问题，而是 **字体** 的原因。先说结论：真机在 CSS 和 Canvas 中，`sans-serif` 字体表现存在差异，导致字符宽度不同，于是在调用 `CanvasRenderingContext2D.measureText` 测量文本宽度，以保证总宽度与 CSS 表现一致时，Canvas 测量出的文本宽度超过 CSS 表现的宽度，从而进入判断并被裁剪。

小程序环境中，测试时 **安卓真机** 在 CSS 样式中生效的字体为 `sans-serif`，Canvas 中生效的字体也为 `sans-serif`。
因为 `sans-serif` 并非一种字体而是 **一类字体**，由于未知原因，小程序在真机 Canvas 中采用了和 CSS 样式中不同的字体。

如下图，字体为 `sans-serif`，其中 **半角字符** 的字体明显不同，字符宽度也不同：
<img width=400 src="https://github.com/ChrisChan13/wxml2canvas-2d/assets/27924290/172eb3e8-bbc5-4ab0-b0e6-e2c9e9e512c2">

如下图，字体为 `Times New Roman`，其中 **全角字符** 的表现不同，但字符宽度相同：
<img width=400 src="https://github.com/ChrisChan13/wxml2canvas-2d/assets/27924290/fc74430e-ffa4-4d2f-936d-57cbb144007e">

综上，暂时没有想出具体方案抹除字体表现的差异，如果你有什么想法，欢迎继续讨论或提交 PR。当然，这个问题会继续跟进。
