### ISSUE TITLE
组件很强大，比wxml-to-canvas和wxml2canvas都好用，不过希望能支持text的换行符

### ISSUE THREAD

**Issue by vaint** [ChrisChan13/wxml2canvas-2d#9]
如题，目前text中带有\n不会换行。

**Comment by vaint** [comment]
我在canvas.js的这两处做了简单的处理，临时解决了。期待更完备的解法~
![20241030-120129](https://github.com/user-attachments/assets/9de53209-e886-4036-8fbe-962ccc1307ed)
![20241030-120134](https://github.com/user-attachments/assets/2456c368-5e74-426e-a097-33e9d5823888)

**Comment by ChrisChan13** [comment]
哈喽，相关问题已在 `^1.0.9` 中修复哦~ 请更新版本检查效果！
